# -------------------- PROD DATABASE --------------------
spring.config.import=optional:file:.env.properties
spring.datasource.url=jdbc:oracle:thin:@//10.16.12.35:1521/FCOSBDEV
spring.datasource.username=BOVOSB
spring.datasource.password=BOVOSB

# Production tuning
spring.jpa.show-sql=false