# -------------------- DEV DATABASE --------------------
# Temporary hardcoded WebLogic test DB configuration.
# TODO: Replace with WebLogic Data Source/JNDI or externalized environment properties before production.
spring.datasource.url=jdbc:oracle:thin:@//localhost:1522/orcl
spring.datasource.username=sys as sysdba
spring.datasource.password=Welcome123

# Optional: debug-friendly
spring.jpa.show-sql=true